from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(930, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.espaceRVB = QtWidgets.QGroupBox(self.centralwidget)
        self.espaceRVB.setGeometry(QtCore.QRect(10, 10, 911, 291))
        self.espaceRVB.setObjectName("espaceRVB")
        self.parcourir = QtWidgets.QPushButton(self.espaceRVB)
        self.parcourir.setGeometry(QtCore.QRect(10, 90, 75, 23))
        self.parcourir.setObjectName("parcourir")
        self.labOrg = QtWidgets.QLabel(self.espaceRVB)
        self.labOrg.setGeometry(QtCore.QRect(120, 10, 91, 20))
        self.labOrg.setObjectName("labOrg")
        self.compB = QtWidgets.QLabel(self.espaceRVB)
        self.compB.setGeometry(QtCore.QRect(720, 40, 181, 181))
        self.compB.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.compB.setText("")
        self.compB.setObjectName("compB")
        self.labBleue = QtWidgets.QLabel(self.espaceRVB)
        self.labBleue.setGeometry(QtCore.QRect(770, 10, 101, 20))
        self.labBleue.setObjectName("labBleue")
        self.afficheB = QtWidgets.QPushButton(self.espaceRVB)
        self.afficheB.setGeometry(QtCore.QRect(760, 250, 121, 23))
        self.afficheB.setObjectName("afficheB")
        self.labVerte = QtWidgets.QLabel(self.espaceRVB)
        self.labVerte.setGeometry(QtCore.QRect(550, 10, 101, 20))
        self.labVerte.setObjectName("labVerte")
        self.afficheV = QtWidgets.QPushButton(self.espaceRVB)
        self.afficheV.setGeometry(QtCore.QRect(550, 250, 121, 23))
        self.afficheV.setObjectName("afficheV")
        self.compV = QtWidgets.QLabel(self.espaceRVB)
        self.compV.setGeometry(QtCore.QRect(510, 40, 191, 181))
        self.compV.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.compV.setText("")
        self.compV.setObjectName("compV")
        self.afficheR = QtWidgets.QPushButton(self.espaceRVB)
        self.afficheR.setGeometry(QtCore.QRect(340, 250, 121, 23))
        self.afficheR.setObjectName("afficheR")
        self.compR = QtWidgets.QLabel(self.espaceRVB)
        self.compR.setGeometry(QtCore.QRect(300, 40, 191, 181))
        self.compR.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.compR.setText("")
        self.compR.setObjectName("compR")
        self.labRouge = QtWidgets.QLabel(self.espaceRVB)
        self.labRouge.setGeometry(QtCore.QRect(340, 10, 101, 20))
        self.labRouge.setObjectName("labRouge")
        self.original = QtWidgets.QLabel(self.espaceRVB)
        self.original.setGeometry(QtCore.QRect(90, 40, 191, 181))
        self.original.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.original.setText("")
        self.original.setObjectName("original")
        self.dimension = QtWidgets.QLabel(self.espaceRVB)
        self.dimension.setGeometry(QtCore.QRect(90, 240, 191, 41))
        self.dimension.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.dimension.setText("")
        self.dimension.setObjectName("dimension")
        self.labDim = QtWidgets.QLabel(self.espaceRVB)
        self.labDim.setGeometry(QtCore.QRect(20, 250, 61, 16))
        self.labDim.setObjectName("labDim")
        self.Nvespcolor = QtWidgets.QGroupBox(self.centralwidget)
        self.Nvespcolor.setGeometry(QtCore.QRect(10, 310, 391, 241))
        self.Nvespcolor.setObjectName("Nvespcolor")
        self.rbYUV = QtWidgets.QRadioButton(self.Nvespcolor)
        self.rbYUV.setGeometry(QtCore.QRect(20, 90, 82, 17))
        self.rbYUV.setObjectName("rbYUV")
        self.rbYCC = QtWidgets.QRadioButton(self.Nvespcolor)
        self.rbYCC.setGeometry(QtCore.QRect(20, 50, 82, 17))
        self.rbYCC.setObjectName("rbYCC")
        self.rbHSV = QtWidgets.QRadioButton(self.Nvespcolor)
        self.rbHSV.setGeometry(QtCore.QRect(20, 130, 82, 17))
        self.rbHSV.setObjectName("rbHSV")
        self.valid = QtWidgets.QPushButton(self.Nvespcolor)
        self.valid.setGeometry(QtCore.QRect(70, 170, 75, 23))
        self.valid.setObjectName("valid")
        self.labNvImg = QtWidgets.QLabel(self.Nvespcolor)
        self.labNvImg.setGeometry(QtCore.QRect(180, 50, 191, 181))
        self.labNvImg.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.labNvImg.setText("")
        self.labNvImg.setObjectName("labNvImg")
        self.Nvimg = QtWidgets.QLabel(self.Nvespcolor)
        self.Nvimg.setGeometry(QtCore.QRect(230, 20, 111, 20))
        self.Nvimg.setObjectName("Nvimg")
        self.contr = QtWidgets.QGroupBox(self.centralwidget)
        self.contr.setGeometry(QtCore.QRect(480, 310, 411, 241))
        self.contr.setObjectName("contr")
        self.cntrValid = QtWidgets.QPushButton(self.contr)
        self.cntrValid.setGeometry(QtCore.QRect(90, 160, 75, 23))
        self.cntrValid.setObjectName("cntrValid")
        self.seuil1 = QtWidgets.QLabel(self.contr)
        self.seuil1.setGeometry(QtCore.QRect(30, 50, 47, 13))
        self.seuil1.setObjectName("seuil1")
        self.seuil2 = QtWidgets.QLabel(self.contr)
        self.seuil2.setGeometry(QtCore.QRect(30, 100, 47, 13))
        self.seuil2.setObjectName("seuil2")
        self.txtS1 = QtWidgets.QTextEdit(self.contr)
        self.txtS1.setGeometry(QtCore.QRect(100, 40, 91, 31))
        self.txtS1.setObjectName("txtS1")
        self.txtS2 = QtWidgets.QTextEdit(self.contr)
        self.txtS2.setGeometry(QtCore.QRect(100, 90, 91, 31))
        self.txtS2.setObjectName("txtS2")
        self.imgCntr = QtWidgets.QLabel(self.contr)
        self.imgCntr.setGeometry(QtCore.QRect(270, 20, 91, 16))
        self.imgCntr.setObjectName("imgCntr")
        self.labImgCntr = QtWidgets.QLabel(self.contr)
        self.labImgCntr.setGeometry(QtCore.QRect(220, 50, 181, 181))
        self.labImgCntr.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.labImgCntr.setText("")
        self.labImgCntr.setObjectName("labImgCntr")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 930, 21))
        self.menubar.setObjectName("menubar")
        self.menuTP1 = QtWidgets.QMenu(self.menubar)
        self.menuTP1.setObjectName("menuTP1")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuTP1.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.espaceRVB.setTitle(_translate("MainWindow", "Espace RVB"))
        self.parcourir.setText(_translate("MainWindow", "parcourir"))
        self.labOrg.setText(_translate("MainWindow", "Image original"))
        self.labBleue.setText(_translate("MainWindow", "Composante bleue"))
        self.afficheB.setText(_translate("MainWindow", "Afficher le canal bleu"))
        self.labVerte.setText(_translate("MainWindow", "Composante verte"))
        self.afficheV.setText(_translate("MainWindow", "Afficher le canal vert"))
        self.afficheR.setText(_translate("MainWindow", "Afficher le canal rouge"))
        self.labRouge.setText(_translate("MainWindow", "Composante rouge"))
        self.labDim.setText(_translate("MainWindow", "Dime"))
        self.Nvespcolor.setTitle(_translate("MainWindow", "Nouvel espace de couleurs"))
        self.rbYUV.setText(_translate("MainWindow", "YUV"))
        self.rbYCC.setText(_translate("MainWindow", "YCbCr"))
        self.rbHSV.setText(_translate("MainWindow", "HSV"))
        self.valid.setText(_translate("MainWindow", "Valider"))
        self.Nvimg.setText(_translate("MainWindow", "Nouvelle image"))
        self.contr.setTitle(_translate("MainWindow", "Contours"))
        self.cntrValid.setText(_translate("MainWindow", "Valider"))
        self.seuil1.setText(_translate("MainWindow", "Seuil 1"))
        self.seuil2.setText(_translate("MainWindow", "Seuil 2"))
        self.imgCntr.setText(_translate("MainWindow", "Image Contours"))
        self.menuTP1.setTitle(_translate("MainWindow", "TP1"))
